<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ComunasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $sqlComunas = "INSERT INTO comunas VALUES (1, 'Arica');
        INSERT INTO comunas VALUES (2, 'Camarones');
        INSERT INTO comunas VALUES (3, 'General Lagos');
        INSERT INTO comunas VALUES (4, 'Putre');
        INSERT INTO comunas VALUES (5, 'Alto Hospicio');
        INSERT INTO comunas VALUES (6, 'Iquique');
        INSERT INTO comunas VALUES (7, 'Camiña');
        INSERT INTO comunas VALUES (8, 'Colchane');
        INSERT INTO comunas VALUES (9, 'Huara');
        INSERT INTO comunas VALUES (10, 'Pica');
        INSERT INTO comunas VALUES (11, 'Pozo Almonte');
        INSERT INTO comunas VALUES (12, 'Tocopilla');
        INSERT INTO comunas VALUES (13, 'María Elena');
        INSERT INTO comunas VALUES (14, 'Calama');
        INSERT INTO comunas VALUES (15, 'Ollague');
        INSERT INTO comunas VALUES (16, 'San Pedro de Atacama');
        INSERT INTO comunas VALUES (17, 'Antofagasta');
        INSERT INTO comunas VALUES (18, 'Mejillones');
        INSERT INTO comunas VALUES (19, 'Sierra Gorda');
        INSERT INTO comunas VALUES (20, 'Taltal');
        INSERT INTO comunas VALUES (21, 'Chañaral');
        INSERT INTO comunas VALUES (22, 'Diego de Almagro');
        INSERT INTO comunas VALUES (23, 'Copiapó');
        INSERT INTO comunas VALUES (24, 'Caldera');
        INSERT INTO comunas VALUES (25, 'Tierra Amarilla');
        INSERT INTO comunas VALUES (26, 'Vallenar');
        INSERT INTO comunas VALUES (27, 'Alto del Carmen');
        INSERT INTO comunas VALUES (28, 'Freirina');
        INSERT INTO comunas VALUES (29, 'Huasco');
        INSERT INTO comunas VALUES (30, 'La Serena');
        INSERT INTO comunas VALUES (31, 'Coquimbo');
        INSERT INTO comunas VALUES (32, 'Andacollo');
        INSERT INTO comunas VALUES (33, 'La Higuera');
        INSERT INTO comunas VALUES (34, 'Paihuano');
        INSERT INTO comunas VALUES (35, 'Vicuña');
        INSERT INTO comunas VALUES (36, 'Ovalle');
        INSERT INTO comunas VALUES (37, 'Combarbalá');
        INSERT INTO comunas VALUES (38, 'Monte Patria');
        INSERT INTO comunas VALUES (39, 'Punitaqui');
        INSERT INTO comunas VALUES (40, 'Río Hurtado');
        INSERT INTO comunas VALUES (41, 'Illapel');
        INSERT INTO comunas VALUES (42, 'Canela');
        INSERT INTO comunas VALUES (43, 'Los Vilos');
        INSERT INTO comunas VALUES (44, 'Salamanca');
        INSERT INTO comunas VALUES (45, 'La Ligua');
        INSERT INTO comunas VALUES (46, 'Cabildo');
        INSERT INTO comunas VALUES (47, 'Zapallar');
        INSERT INTO comunas VALUES (48, 'Papudo');
        INSERT INTO comunas VALUES (49, 'Petorca');
        INSERT INTO comunas VALUES (50, 'Los Andes');
        INSERT INTO comunas VALUES (51, 'San Esteban');
        INSERT INTO comunas VALUES (52, 'Calle Larga');
        INSERT INTO comunas VALUES (53, 'Rinconada');
        INSERT INTO comunas VALUES (54, 'San Felipe');
        INSERT INTO comunas VALUES (55, 'Llaillay');
        INSERT INTO comunas VALUES (56, 'Putaendo');
        INSERT INTO comunas VALUES (57, 'Santa María');
        INSERT INTO comunas VALUES (58, 'Catemu');
        INSERT INTO comunas VALUES (59, 'Panquehue');
        INSERT INTO comunas VALUES (60, 'Quillota');
        INSERT INTO comunas VALUES (61, 'La Cruz');
        INSERT INTO comunas VALUES (62, 'La Calera');
        INSERT INTO comunas VALUES (63, 'Nogales');
        INSERT INTO comunas VALUES (64, 'Hijuelas');
        INSERT INTO comunas VALUES (65, 'Valparaíso');
        INSERT INTO comunas VALUES (66, 'Viña del Mar');
        INSERT INTO comunas VALUES (67, 'Concón');
        INSERT INTO comunas VALUES (68, 'Quintero');
        INSERT INTO comunas VALUES (69, 'Puchuncaví');
        INSERT INTO comunas VALUES (70, 'Casablanca');
        INSERT INTO comunas VALUES (71, 'Juan Fernández');
        INSERT INTO comunas VALUES (72, 'San Antonio');
        INSERT INTO comunas VALUES (73, 'Cartagena');
        INSERT INTO comunas VALUES (74, 'El Tabo');
        INSERT INTO comunas VALUES (75, 'El Quisco');
        INSERT INTO comunas VALUES (76, 'Algarrobo');
        INSERT INTO comunas VALUES (77, 'Santo Domingo');
        INSERT INTO comunas VALUES (78, 'Isla de Pascua');
        INSERT INTO comunas VALUES (79, 'Quilpué');
        INSERT INTO comunas VALUES (80, 'Limache');
        INSERT INTO comunas VALUES (81, 'Olmué');
        INSERT INTO comunas VALUES (82, 'Villa Alemana');
        INSERT INTO comunas VALUES (83, 'Colina');
        INSERT INTO comunas VALUES (84, 'Lampa');
        INSERT INTO comunas VALUES (85, 'Tiltil');
        INSERT INTO comunas VALUES (86, 'Santiago');
        INSERT INTO comunas VALUES (87, 'Vitacura');
        INSERT INTO comunas VALUES (88, 'San Ramón');
        INSERT INTO comunas VALUES (89, 'San Miguel');
        INSERT INTO comunas VALUES (90, 'San Joaquín');
        INSERT INTO comunas VALUES (91, 'Renca');
        INSERT INTO comunas VALUES (92, 'Recoleta');
        INSERT INTO comunas VALUES (93, 'Quinta Normal');
        INSERT INTO comunas VALUES (94, 'Quilicura');
        INSERT INTO comunas VALUES (95, 'Pudahuel');
        INSERT INTO comunas VALUES (96, 'Providencia');
        INSERT INTO comunas VALUES (97, 'Peñalolén');
        INSERT INTO comunas VALUES (98, 'Pedro Aguirre Cerda');
        INSERT INTO comunas VALUES (99, 'Ñuñoa');
        INSERT INTO comunas VALUES (100, 'Maipú');
        INSERT INTO comunas VALUES (101, 'Macul');
        INSERT INTO comunas VALUES (102, 'Lo Prado');
        INSERT INTO comunas VALUES (103, 'Lo Espejo');
        INSERT INTO comunas VALUES (104, 'Lo Barnechea');
        INSERT INTO comunas VALUES (105, 'Las Condes');
        INSERT INTO comunas VALUES (106, 'La Reina');
        INSERT INTO comunas VALUES (107, 'La Pintana');
        INSERT INTO comunas VALUES (108, 'La Granja');
        INSERT INTO comunas VALUES (109, 'La Florida');
        INSERT INTO comunas VALUES (110, 'La Cisterna');
        INSERT INTO comunas VALUES (111, 'Independencia');
        INSERT INTO comunas VALUES (112, 'Huechuraba');
        INSERT INTO comunas VALUES (113, 'Estación Central');
        INSERT INTO comunas VALUES (114, 'El Bosque');
        INSERT INTO comunas VALUES (115, 'Conchalí');
        INSERT INTO comunas VALUES (116, 'Cerro Navia');
        INSERT INTO comunas VALUES (117, 'Cerrillos');
        INSERT INTO comunas VALUES (118, 'Puente Alto');
        INSERT INTO comunas VALUES (119, 'San José de Maipo');
        INSERT INTO comunas VALUES (120, 'Pirque');
        INSERT INTO comunas VALUES (121, 'San Bernardo');
        INSERT INTO comunas VALUES (122, 'Buin');
        INSERT INTO comunas VALUES (123, 'Paine');
        INSERT INTO comunas VALUES (124, 'Calera de Tango');
        INSERT INTO comunas VALUES (125, 'Melipilla');
        INSERT INTO comunas VALUES (126, 'Alhué');
        INSERT INTO comunas VALUES (127, 'Curacaví');
        INSERT INTO comunas VALUES (128, 'María Pinto');
        INSERT INTO comunas VALUES (129, 'San Pedro');
        INSERT INTO comunas VALUES (130, 'Isla de Maipo');
        INSERT INTO comunas VALUES (131, 'El Monte');
        INSERT INTO comunas VALUES (132, 'Padre Hurtado');
        INSERT INTO comunas VALUES (133, 'Peñaflor');
        INSERT INTO comunas VALUES (134, 'Talagante');
        INSERT INTO comunas VALUES (135, 'Codegua');
        INSERT INTO comunas VALUES (136, 'Coínco');
        INSERT INTO comunas VALUES (137, 'Coltauco');
        INSERT INTO comunas VALUES (138, 'Doñihue');
        INSERT INTO comunas VALUES (139, 'Graneros');
        INSERT INTO comunas VALUES (140, 'Las Cabras');
        INSERT INTO comunas VALUES (141, 'Machalí');
        INSERT INTO comunas VALUES (142, 'Malloa');
        INSERT INTO comunas VALUES (143, 'Mostazal');
        INSERT INTO comunas VALUES (144, 'Olivar');
        INSERT INTO comunas VALUES (145, 'Peumo');
        INSERT INTO comunas VALUES (146, 'Pichidegua');
        INSERT INTO comunas VALUES (147, 'Quinta de Tilcoco');
        INSERT INTO comunas VALUES (148, 'Rancagua');
        INSERT INTO comunas VALUES (149, 'Rengo');
        INSERT INTO comunas VALUES (150, 'Requínoa');
        INSERT INTO comunas VALUES (151, 'San Vicente de Tagua Tagua');
        INSERT INTO comunas VALUES (152, 'Chépica');
        INSERT INTO comunas VALUES (153, 'Chimbarongo');
        INSERT INTO comunas VALUES (154, 'Lolol');
        INSERT INTO comunas VALUES (155, 'Nancagua');
        INSERT INTO comunas VALUES (156, 'Palmilla');
        INSERT INTO comunas VALUES (157, 'Peralillo');
        INSERT INTO comunas VALUES (158, 'Placilla');
        INSERT INTO comunas VALUES (159, 'Pumanque');
        INSERT INTO comunas VALUES (160, 'San Fernando');
        INSERT INTO comunas VALUES (161, 'Santa Cruz');
        INSERT INTO comunas VALUES (162, 'La Estrella');
        INSERT INTO comunas VALUES (163, 'Litueche');
        INSERT INTO comunas VALUES (164, 'Marchigüe');
        INSERT INTO comunas VALUES (165, 'Navidad');
        INSERT INTO comunas VALUES (166, 'Paredones');
        INSERT INTO comunas VALUES (167, 'Pichilemu');
        INSERT INTO comunas VALUES (168, 'Curicó');
        INSERT INTO comunas VALUES (169, 'Hualañé');
        INSERT INTO comunas VALUES (170, 'Licantén');
        INSERT INTO comunas VALUES (171, 'Molina');
        INSERT INTO comunas VALUES (172, 'Rauco');
        INSERT INTO comunas VALUES (173, 'Romeral');
        INSERT INTO comunas VALUES (174, 'Sagrada Familia');
        INSERT INTO comunas VALUES (175, 'Teno');
        INSERT INTO comunas VALUES (176, 'Vichuquén');
        INSERT INTO comunas VALUES (177, 'Talca');
        INSERT INTO comunas VALUES (178, 'San Clemente');
        INSERT INTO comunas VALUES (179, 'Pelarco');
        INSERT INTO comunas VALUES (180, 'Pencahue');
        INSERT INTO comunas VALUES (181, 'Maule');
        INSERT INTO comunas VALUES (182, 'San Rafael');
        INSERT INTO comunas VALUES (183, 'Curepto');
        INSERT INTO comunas VALUES (184, 'Constitución');
        INSERT INTO comunas VALUES (185, 'Empedrado');
        INSERT INTO comunas VALUES (186, 'Río Claro');
        INSERT INTO comunas VALUES (187, 'Linares');
        INSERT INTO comunas VALUES (188, 'San Javier');
        INSERT INTO comunas VALUES (189, 'Parral');
        INSERT INTO comunas VALUES (190, 'Villa Alegre');
        INSERT INTO comunas VALUES (191, 'Longaví');
        INSERT INTO comunas VALUES (192, 'Colbún');
        INSERT INTO comunas VALUES (193, 'Retiro');
        INSERT INTO comunas VALUES (194, 'Yerbas Buenas');
        INSERT INTO comunas VALUES (195, 'Cauquenes');
        INSERT INTO comunas VALUES (196, 'Chanco');
        INSERT INTO comunas VALUES (197, 'Pelluhue');
        INSERT INTO comunas VALUES (198, 'Bulnes');
        INSERT INTO comunas VALUES (199, 'Chillán');
        INSERT INTO comunas VALUES (200, 'Chillán Viejo');
        INSERT INTO comunas VALUES (201, 'El Carmen');
        INSERT INTO comunas VALUES (202, 'Pemuco');
        INSERT INTO comunas VALUES (203, 'Pinto');
        INSERT INTO comunas VALUES (204, 'Quillón');
        INSERT INTO comunas VALUES (205, 'San Ignacio');
        INSERT INTO comunas VALUES (206, 'Yungay');
        INSERT INTO comunas VALUES (207, 'Cobquecura');
        INSERT INTO comunas VALUES (208, 'Coelemu');
        INSERT INTO comunas VALUES (209, 'Ninhue');
        INSERT INTO comunas VALUES (210, 'Portezuelo');
        INSERT INTO comunas VALUES (211, 'Quirihue');
        INSERT INTO comunas VALUES (212, 'Ránquil');
        INSERT INTO comunas VALUES (213, 'Treguaco');
        INSERT INTO comunas VALUES (214, 'San Carlos');
        INSERT INTO comunas VALUES (215, 'Coihueco');
        INSERT INTO comunas VALUES (216, 'San Nicolás');
        INSERT INTO comunas VALUES (217, 'Ñiquén');
        INSERT INTO comunas VALUES (218, 'San Fabián');
        INSERT INTO comunas VALUES (219, 'Alto Biobío');
        INSERT INTO comunas VALUES (220, 'Antuco');
        INSERT INTO comunas VALUES (221, 'Cabrero');
        INSERT INTO comunas VALUES (222, 'Laja');
        INSERT INTO comunas VALUES (223, 'Los Ángeles');
        INSERT INTO comunas VALUES (224, 'Mulchén');
        INSERT INTO comunas VALUES (225, 'Nacimiento');
        INSERT INTO comunas VALUES (226, 'Negrete');
        INSERT INTO comunas VALUES (227, 'Quilaco');
        INSERT INTO comunas VALUES (228, 'Quilleco');
        INSERT INTO comunas VALUES (229, 'San Rosendo');
        INSERT INTO comunas VALUES (230, 'Santa Bárbara');
        INSERT INTO comunas VALUES (231, 'Tucapel');
        INSERT INTO comunas VALUES (232, 'Yumbel');
        INSERT INTO comunas VALUES (233, 'Concepción');
        INSERT INTO comunas VALUES (234, 'Coronel');
        INSERT INTO comunas VALUES (235, 'Chiguayante');
        INSERT INTO comunas VALUES (236, 'Florida');
        INSERT INTO comunas VALUES (237, 'Hualpén');
        INSERT INTO comunas VALUES (238, 'Hualqui');
        INSERT INTO comunas VALUES (239, 'Lota');
        INSERT INTO comunas VALUES (240, 'Penco');
        INSERT INTO comunas VALUES (241, 'San Pedro de La Paz');
        INSERT INTO comunas VALUES (242, 'Santa Juana');
        INSERT INTO comunas VALUES (243, 'Talcahuano');
        INSERT INTO comunas VALUES (244, 'Tomé');
        INSERT INTO comunas VALUES (245, 'Arauco');
        INSERT INTO comunas VALUES (246, 'Cañete');
        INSERT INTO comunas VALUES (247, 'Contulmo');
        INSERT INTO comunas VALUES (248, 'Curanilahue');
        INSERT INTO comunas VALUES (249, 'Lebu');
        INSERT INTO comunas VALUES (250, 'Los Álamos');
        INSERT INTO comunas VALUES (251, 'Tirúa');
        INSERT INTO comunas VALUES (252, 'Angol');
        INSERT INTO comunas VALUES (253, 'Collipulli');
        INSERT INTO comunas VALUES (254, 'Curacautín');
        INSERT INTO comunas VALUES (255, 'Ercilla');
        INSERT INTO comunas VALUES (256, 'Lonquimay');
        INSERT INTO comunas VALUES (257, 'Los Sauces');
        INSERT INTO comunas VALUES (258, 'Lumaco');
        INSERT INTO comunas VALUES (259, 'Purén');
        INSERT INTO comunas VALUES (260, 'Renaico');
        INSERT INTO comunas VALUES (261, 'Traiguén');
        INSERT INTO comunas VALUES (262, 'Victoria');
        INSERT INTO comunas VALUES (263, 'Temuco');
        INSERT INTO comunas VALUES (264, 'Carahue');
        INSERT INTO comunas VALUES (265, 'Cholchol');
        INSERT INTO comunas VALUES (266, 'Cunco');
        INSERT INTO comunas VALUES (267, 'Curarrehue');
        INSERT INTO comunas VALUES (268, 'Freire');
        INSERT INTO comunas VALUES (269, 'Galvarino');
        INSERT INTO comunas VALUES (270, 'Gorbea');
        INSERT INTO comunas VALUES (271, 'Lautaro');
        INSERT INTO comunas VALUES (272, 'Loncoche');
        INSERT INTO comunas VALUES (273, 'Melipeuco');
        INSERT INTO comunas VALUES (274, 'Nueva Imperial');
        INSERT INTO comunas VALUES (275, 'Padre Las Casas');
        INSERT INTO comunas VALUES (276, 'Perquenco');
        INSERT INTO comunas VALUES (277, 'Pitrufquén');
        INSERT INTO comunas VALUES (278, 'Pucón');
        INSERT INTO comunas VALUES (279, 'Saavedra');
        INSERT INTO comunas VALUES (280, 'Teodoro Schmidt');
        INSERT INTO comunas VALUES (281, 'Toltén');
        INSERT INTO comunas VALUES (282, 'Vilcún');
        INSERT INTO comunas VALUES (283, 'Villarrica');
        INSERT INTO comunas VALUES (284, 'Valdivia');
        INSERT INTO comunas VALUES (285, 'Corral');
        INSERT INTO comunas VALUES (286, 'Lanco');
        INSERT INTO comunas VALUES (287, 'Los Lagos');
        INSERT INTO comunas VALUES (288, 'Máfil');
        INSERT INTO comunas VALUES (289, 'Mariquina');
        INSERT INTO comunas VALUES (290, 'Paillaco');
        INSERT INTO comunas VALUES (291, 'Panguipulli');
        INSERT INTO comunas VALUES (292, 'La Unión');
        INSERT INTO comunas VALUES (293, 'Futrono');
        INSERT INTO comunas VALUES (294, 'Lago Ranco');
        INSERT INTO comunas VALUES (295, 'Río Bueno');
        INSERT INTO comunas VALUES (297, 'Osorno');
        INSERT INTO comunas VALUES (298, 'Puerto Octay');
        INSERT INTO comunas VALUES (299, 'Purranque');
        INSERT INTO comunas VALUES (300, 'Puyehue');
        INSERT INTO comunas VALUES (301, 'Río Negro');
        INSERT INTO comunas VALUES (302, 'San Juan de la Costa');
        INSERT INTO comunas VALUES (303, 'San Pablo');
        INSERT INTO comunas VALUES (304, 'Calbuco');
        INSERT INTO comunas VALUES (305, 'Cochamó');
        INSERT INTO comunas VALUES (306, 'Fresia');
        INSERT INTO comunas VALUES (307, 'Frutillar');
        INSERT INTO comunas VALUES (308, 'Llanquihue');
        INSERT INTO comunas VALUES (309, 'Los Muermos');
        INSERT INTO comunas VALUES (310, 'Maullín');
        INSERT INTO comunas VALUES (311, 'Puerto Montt');
        INSERT INTO comunas VALUES (312, 'Puerto Varas');
        INSERT INTO comunas VALUES (313, 'Ancud');
        INSERT INTO comunas VALUES (314, 'Castro');
        INSERT INTO comunas VALUES (315, 'Chonchi');
        INSERT INTO comunas VALUES (316, 'Curaco de Vélez');
        INSERT INTO comunas VALUES (317, 'Dalcahue');
        INSERT INTO comunas VALUES (318, 'Puqueldón');
        INSERT INTO comunas VALUES (319, 'Queilén');
        INSERT INTO comunas VALUES (320, 'Quellón');
        INSERT INTO comunas VALUES (321, 'Quemchi');
        INSERT INTO comunas VALUES (322, 'Quinchao');
        INSERT INTO comunas VALUES (323, 'Chaitén');
        INSERT INTO comunas VALUES (324, 'Futaleufú');
        INSERT INTO comunas VALUES (325, 'Hualaihué');
        INSERT INTO comunas VALUES (326, 'Palena');
        INSERT INTO comunas VALUES (327, 'Lago Verde');
        INSERT INTO comunas VALUES (328, 'Coihaique');
        INSERT INTO comunas VALUES (329, 'Aysén');
        INSERT INTO comunas VALUES (330, 'Cisnes');
        INSERT INTO comunas VALUES (331, 'Guaitecas');
        INSERT INTO comunas VALUES (332, 'Río Ibáñez');
        INSERT INTO comunas VALUES (333, 'Chile Chico');
        INSERT INTO comunas VALUES (334, 'Cochrane');
        INSERT INTO comunas VALUES (335, 'O''higgins');
        INSERT INTO comunas VALUES (336, 'Tortel');
        INSERT INTO comunas VALUES (337, 'Natales');
        INSERT INTO comunas VALUES (338, 'Torres del Paine');
        INSERT INTO comunas VALUES (339, 'Laguna Blanca');
        INSERT INTO comunas VALUES (340, 'Punta Arenas');
        INSERT INTO comunas VALUES (341, 'Río Verde');
        INSERT INTO comunas VALUES (342, 'San Gregorio');
        INSERT INTO comunas VALUES (343, 'Porvenir');
        INSERT INTO comunas VALUES (344, 'Primavera');
        INSERT INTO comunas VALUES (345, 'Timaukel');
        INSERT INTO comunas VALUES (346, 'Cabo de Hornos');
        INSERT INTO comunas VALUES (347, 'Antártica');
        INSERT INTO comunas VALUES (348, 'San Francisco de Mostazal');";

        DB::unprepared($sqlComunas);
    }
}
