<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ComunasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $sqlComunas = 'INSERT INTO "comunas" ("id", "nombre") VALUES (1, "Arica");
        INSERT INTO "comunas" ("id", "nombre") VALUES (2, "Camarones");
        INSERT INTO "comunas" ("id", "nombre") VALUES (3, "General Lagos");
        INSERT INTO "comunas" ("id", "nombre") VALUES (4, "Putre");
        INSERT INTO "comunas" ("id", "nombre") VALUES (5, "Alto Hospicio");
        INSERT INTO "comunas" ("id", "nombre") VALUES (6, "Iquique");
        INSERT INTO "comunas" ("id", "nombre") VALUES (7, "Camiña");
        INSERT INTO "comunas" ("id", "nombre") VALUES (8, "Colchane");
        INSERT INTO "comunas" ("id", "nombre") VALUES (9, "Huara");
        INSERT INTO "comunas" ("id", "nombre") VALUES (10, "Pica");
        INSERT INTO "comunas" ("id", "nombre") VALUES (11, "Pozo Almonte");
        INSERT INTO "comunas" ("id", "nombre") VALUES (12, "Tocopilla");
        INSERT INTO "comunas" ("id", "nombre") VALUES (13, "María Elena");
        INSERT INTO "comunas" ("id", "nombre") VALUES (14, "Calama");
        INSERT INTO "comunas" ("id", "nombre") VALUES (15, "Ollague");
        INSERT INTO "comunas" ("id", "nombre") VALUES (16, "San Pedro de Atacama");
        INSERT INTO "comunas" ("id", "nombre") VALUES (17, "Antofagasta");
        INSERT INTO "comunas" ("id", "nombre") VALUES (18, "Mejillones");
        INSERT INTO "comunas" ("id", "nombre") VALUES (19, "Sierra Gorda");
        INSERT INTO "comunas" ("id", "nombre") VALUES (20, "Taltal");
        INSERT INTO "comunas" ("id", "nombre") VALUES (21, "Chañaral");
        INSERT INTO "comunas" ("id", "nombre") VALUES (22, "Diego de Almagro");
        INSERT INTO "comunas" ("id", "nombre") VALUES (23, "Copiapó");
        INSERT INTO "comunas" ("id", "nombre") VALUES (24, "Caldera");
        INSERT INTO "comunas" ("id", "nombre") VALUES (25, "Tierra Amarilla");
        INSERT INTO "comunas" ("id", "nombre") VALUES (26, "Vallenar");
        INSERT INTO "comunas" ("id", "nombre") VALUES (27, "Alto del Carmen");
        INSERT INTO "comunas" ("id", "nombre") VALUES (28, "Freirina");
        INSERT INTO "comunas" ("id", "nombre") VALUES (29, "Huasco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (30, "La Serena");
        INSERT INTO "comunas" ("id", "nombre") VALUES (31, "Coquimbo");
        INSERT INTO "comunas" ("id", "nombre") VALUES (32, "Andacollo");
        INSERT INTO "comunas" ("id", "nombre") VALUES (33, "La Higuera");
        INSERT INTO "comunas" ("id", "nombre") VALUES (34, "Paihuano");
        INSERT INTO "comunas" ("id", "nombre") VALUES (35, "Vicuña");
        INSERT INTO "comunas" ("id", "nombre") VALUES (36, "Ovalle");
        INSERT INTO "comunas" ("id", "nombre") VALUES (37, "Combarbalá");
        INSERT INTO "comunas" ("id", "nombre") VALUES (38, "Monte Patria");
        INSERT INTO "comunas" ("id", "nombre") VALUES (39, "Punitaqui");
        INSERT INTO "comunas" ("id", "nombre") VALUES (40, "Río Hurtado");
        INSERT INTO "comunas" ("id", "nombre") VALUES (41, "Illapel");
        INSERT INTO "comunas" ("id", "nombre") VALUES (42, "Canela");
        INSERT INTO "comunas" ("id", "nombre") VALUES (43, "Los Vilos");
        INSERT INTO "comunas" ("id", "nombre") VALUES (44, "Salamanca");
        INSERT INTO "comunas" ("id", "nombre") VALUES (45, "La Ligua");
        INSERT INTO "comunas" ("id", "nombre") VALUES (46, "Cabildo");
        INSERT INTO "comunas" ("id", "nombre") VALUES (47, "Zapallar");
        INSERT INTO "comunas" ("id", "nombre") VALUES (48, "Papudo");
        INSERT INTO "comunas" ("id", "nombre") VALUES (49, "Petorca");
        INSERT INTO "comunas" ("id", "nombre") VALUES (50, "Los Andes");
        INSERT INTO "comunas" ("id", "nombre") VALUES (51, "San Esteban");
        INSERT INTO "comunas" ("id", "nombre") VALUES (52, "Calle Larga");
        INSERT INTO "comunas" ("id", "nombre") VALUES (53, "Rinconada");
        INSERT INTO "comunas" ("id", "nombre") VALUES (54, "San Felipe");
        INSERT INTO "comunas" ("id", "nombre") VALUES (55, "Llaillay");
        INSERT INTO "comunas" ("id", "nombre") VALUES (56, "Putaendo");
        INSERT INTO "comunas" ("id", "nombre") VALUES (57, "Santa María");
        INSERT INTO "comunas" ("id", "nombre") VALUES (58, "Catemu");
        INSERT INTO "comunas" ("id", "nombre") VALUES (59, "Panquehue");
        INSERT INTO "comunas" ("id", "nombre") VALUES (60, "Quillota");
        INSERT INTO "comunas" ("id", "nombre") VALUES (61, "La Cruz");
        INSERT INTO "comunas" ("id", "nombre") VALUES (62, "La Calera");
        INSERT INTO "comunas" ("id", "nombre") VALUES (63, "Nogales");
        INSERT INTO "comunas" ("id", "nombre") VALUES (64, "Hijuelas");
        INSERT INTO "comunas" ("id", "nombre") VALUES (65, "Valparaíso");
        INSERT INTO "comunas" ("id", "nombre") VALUES (66, "Viña del Mar");
        INSERT INTO "comunas" ("id", "nombre") VALUES (67, "Concón");
        INSERT INTO "comunas" ("id", "nombre") VALUES (68, "Quintero");
        INSERT INTO "comunas" ("id", "nombre") VALUES (69, "Puchuncaví");
        INSERT INTO "comunas" ("id", "nombre") VALUES (70, "Casablanca");
        INSERT INTO "comunas" ("id", "nombre") VALUES (71, "Juan Fernández");
        INSERT INTO "comunas" ("id", "nombre") VALUES (72, "San Antonio");
        INSERT INTO "comunas" ("id", "nombre") VALUES (73, "Cartagena");
        INSERT INTO "comunas" ("id", "nombre") VALUES (74, "El Tabo");
        INSERT INTO "comunas" ("id", "nombre") VALUES (75, "El Quisco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (76, "Algarrobo");
        INSERT INTO "comunas" ("id", "nombre") VALUES (77, "Santo Domingo");
        INSERT INTO "comunas" ("id", "nombre") VALUES (78, "Isla de Pascua");
        INSERT INTO "comunas" ("id", "nombre") VALUES (79, "Quilpué");
        INSERT INTO "comunas" ("id", "nombre") VALUES (80, "Limache");
        INSERT INTO "comunas" ("id", "nombre") VALUES (81, "Olmué");
        INSERT INTO "comunas" ("id", "nombre") VALUES (82, "Villa Alemana");
        INSERT INTO "comunas" ("id", "nombre") VALUES (83, "Colina");
        INSERT INTO "comunas" ("id", "nombre") VALUES (84, "Lampa");
        INSERT INTO "comunas" ("id", "nombre") VALUES (85, "Tiltil");
        INSERT INTO "comunas" ("id", "nombre") VALUES (86, "Santiago");
        INSERT INTO "comunas" ("id", "nombre") VALUES (87, "Vitacura");
        INSERT INTO "comunas" ("id", "nombre") VALUES (88, "San Ramón");
        INSERT INTO "comunas" ("id", "nombre") VALUES (89, "San Miguel");
        INSERT INTO "comunas" ("id", "nombre") VALUES (90, "San Joaquín");
        INSERT INTO "comunas" ("id", "nombre") VALUES (91, "Renca");
        INSERT INTO "comunas" ("id", "nombre") VALUES (92, "Recoleta");
        INSERT INTO "comunas" ("id", "nombre") VALUES (93, "Quinta Normal");
        INSERT INTO "comunas" ("id", "nombre") VALUES (94, "Quilicura");
        INSERT INTO "comunas" ("id", "nombre") VALUES (95, "Pudahuel");
        INSERT INTO "comunas" ("id", "nombre") VALUES (96, "Providencia");
        INSERT INTO "comunas" ("id", "nombre") VALUES (97, "Peñalolén");
        INSERT INTO "comunas" ("id", "nombre") VALUES (98, "Pedro Aguirre Cerda");
        INSERT INTO "comunas" ("id", "nombre") VALUES (99, "Ñuñoa");
        INSERT INTO "comunas" ("id", "nombre") VALUES (100, "Maipú");
        INSERT INTO "comunas" ("id", "nombre") VALUES (101, "Macul");
        INSERT INTO "comunas" ("id", "nombre") VALUES (102, "Lo Prado");
        INSERT INTO "comunas" ("id", "nombre") VALUES (103, "Lo Espejo");
        INSERT INTO "comunas" ("id", "nombre") VALUES (104, "Lo Barnechea");
        INSERT INTO "comunas" ("id", "nombre") VALUES (105, "Las Condes");
        INSERT INTO "comunas" ("id", "nombre") VALUES (106, "La Reina");
        INSERT INTO "comunas" ("id", "nombre") VALUES (107, "La Pintana");
        INSERT INTO "comunas" ("id", "nombre") VALUES (108, "La Granja");
        INSERT INTO "comunas" ("id", "nombre") VALUES (109, "La Florida");
        INSERT INTO "comunas" ("id", "nombre") VALUES (110, "La Cisterna");
        INSERT INTO "comunas" ("id", "nombre") VALUES (111, "Independencia");
        INSERT INTO "comunas" ("id", "nombre") VALUES (112, "Huechuraba");
        INSERT INTO "comunas" ("id", "nombre") VALUES (113, "Estación Central");
        INSERT INTO "comunas" ("id", "nombre") VALUES (114, "El Bosque");
        INSERT INTO "comunas" ("id", "nombre") VALUES (115, "Conchalí");
        INSERT INTO "comunas" ("id", "nombre") VALUES (116, "Cerro Navia");
        INSERT INTO "comunas" ("id", "nombre") VALUES (117, "Cerrillos");
        INSERT INTO "comunas" ("id", "nombre") VALUES (118, "Puente Alto");
        INSERT INTO "comunas" ("id", "nombre") VALUES (119, "San José de Maipo");
        INSERT INTO "comunas" ("id", "nombre") VALUES (120, "Pirque");
        INSERT INTO "comunas" ("id", "nombre") VALUES (121, "San Bernardo");
        INSERT INTO "comunas" ("id", "nombre") VALUES (122, "Buin");
        INSERT INTO "comunas" ("id", "nombre") VALUES (123, "Paine");
        INSERT INTO "comunas" ("id", "nombre") VALUES (124, "Calera de Tango");
        INSERT INTO "comunas" ("id", "nombre") VALUES (125, "Melipilla");
        INSERT INTO "comunas" ("id", "nombre") VALUES (126, "Alhué");
        INSERT INTO "comunas" ("id", "nombre") VALUES (127, "Curacaví");
        INSERT INTO "comunas" ("id", "nombre") VALUES (128, "María Pinto");
        INSERT INTO "comunas" ("id", "nombre") VALUES (129, "San Pedro");
        INSERT INTO "comunas" ("id", "nombre") VALUES (130, "Isla de Maipo");
        INSERT INTO "comunas" ("id", "nombre") VALUES (131, "El Monte");
        INSERT INTO "comunas" ("id", "nombre") VALUES (132, "Padre Hurtado");
        INSERT INTO "comunas" ("id", "nombre") VALUES (133, "Peñaflor");
        INSERT INTO "comunas" ("id", "nombre") VALUES (134, "Talagante");
        INSERT INTO "comunas" ("id", "nombre") VALUES (135, "Codegua");
        INSERT INTO "comunas" ("id", "nombre") VALUES (136, "Coínco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (137, "Coltauco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (138, "Doñihue");
        INSERT INTO "comunas" ("id", "nombre") VALUES (139, "Graneros");
        INSERT INTO "comunas" ("id", "nombre") VALUES (140, "Las Cabras");
        INSERT INTO "comunas" ("id", "nombre") VALUES (141, "Machalí");
        INSERT INTO "comunas" ("id", "nombre") VALUES (142, "Malloa");
        INSERT INTO "comunas" ("id", "nombre") VALUES (143, "Mostazal");
        INSERT INTO "comunas" ("id", "nombre") VALUES (144, "Olivar");
        INSERT INTO "comunas" ("id", "nombre") VALUES (145, "Peumo");
        INSERT INTO "comunas" ("id", "nombre") VALUES (146, "Pichidegua");
        INSERT INTO "comunas" ("id", "nombre") VALUES (147, "Quinta de Tilcoco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (148, "Rancagua");
        INSERT INTO "comunas" ("id", "nombre") VALUES (149, "Rengo");
        INSERT INTO "comunas" ("id", "nombre") VALUES (150, "Requínoa");
        INSERT INTO "comunas" ("id", "nombre") VALUES (151, "San Vicente de Tagua Tagua");
        INSERT INTO "comunas" ("id", "nombre") VALUES (152, "Chépica");
        INSERT INTO "comunas" ("id", "nombre") VALUES (153, "Chimbarongo");
        INSERT INTO "comunas" ("id", "nombre") VALUES (154, "Lolol");
        INSERT INTO "comunas" ("id", "nombre") VALUES (155, "Nancagua");
        INSERT INTO "comunas" ("id", "nombre") VALUES (156, "Palmilla");
        INSERT INTO "comunas" ("id", "nombre") VALUES (157, "Peralillo");
        INSERT INTO "comunas" ("id", "nombre") VALUES (158, "Placilla");
        INSERT INTO "comunas" ("id", "nombre") VALUES (159, "Pumanque");
        INSERT INTO "comunas" ("id", "nombre") VALUES (160, "San Fernando");
        INSERT INTO "comunas" ("id", "nombre") VALUES (161, "Santa Cruz");
        INSERT INTO "comunas" ("id", "nombre") VALUES (162, "La Estrella");
        INSERT INTO "comunas" ("id", "nombre") VALUES (163, "Litueche");
        INSERT INTO "comunas" ("id", "nombre") VALUES (164, "Marchigüe");
        INSERT INTO "comunas" ("id", "nombre") VALUES (165, "Navidad");
        INSERT INTO "comunas" ("id", "nombre") VALUES (166, "Paredones");
        INSERT INTO "comunas" ("id", "nombre") VALUES (167, "Pichilemu");
        INSERT INTO "comunas" ("id", "nombre") VALUES (168, "Curicó");
        INSERT INTO "comunas" ("id", "nombre") VALUES (169, "Hualañé");
        INSERT INTO "comunas" ("id", "nombre") VALUES (170, "Licantén");
        INSERT INTO "comunas" ("id", "nombre") VALUES (171, "Molina");
        INSERT INTO "comunas" ("id", "nombre") VALUES (172, "Rauco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (173, "Romeral");
        INSERT INTO "comunas" ("id", "nombre") VALUES (174, "Sagrada Familia");
        INSERT INTO "comunas" ("id", "nombre") VALUES (175, "Teno");
        INSERT INTO "comunas" ("id", "nombre") VALUES (176, "Vichuquén");
        INSERT INTO "comunas" ("id", "nombre") VALUES (177, "Talca");
        INSERT INTO "comunas" ("id", "nombre") VALUES (178, "San Clemente");
        INSERT INTO "comunas" ("id", "nombre") VALUES (179, "Pelarco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (180, "Pencahue");
        INSERT INTO "comunas" ("id", "nombre") VALUES (181, "Maule");
        INSERT INTO "comunas" ("id", "nombre") VALUES (182, "San Rafael");
        INSERT INTO "comunas" ("id", "nombre") VALUES (183, "Curepto");
        INSERT INTO "comunas" ("id", "nombre") VALUES (184, "Constitución");
        INSERT INTO "comunas" ("id", "nombre") VALUES (185, "Empedrado");
        INSERT INTO "comunas" ("id", "nombre") VALUES (186, "Río Claro");
        INSERT INTO "comunas" ("id", "nombre") VALUES (187, "Linares");
        INSERT INTO "comunas" ("id", "nombre") VALUES (188, "San Javier");
        INSERT INTO "comunas" ("id", "nombre") VALUES (189, "Parral");
        INSERT INTO "comunas" ("id", "nombre") VALUES (190, "Villa Alegre");
        INSERT INTO "comunas" ("id", "nombre") VALUES (191, "Longaví");
        INSERT INTO "comunas" ("id", "nombre") VALUES (192, "Colbún");
        INSERT INTO "comunas" ("id", "nombre") VALUES (193, "Retiro");
        INSERT INTO "comunas" ("id", "nombre") VALUES (194, "Yerbas Buenas");
        INSERT INTO "comunas" ("id", "nombre") VALUES (195, "Cauquenes");
        INSERT INTO "comunas" ("id", "nombre") VALUES (196, "Chanco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (197, "Pelluhue");
        INSERT INTO "comunas" ("id", "nombre") VALUES (198, "Bulnes");
        INSERT INTO "comunas" ("id", "nombre") VALUES (199, "Chillán");
        INSERT INTO "comunas" ("id", "nombre") VALUES (200, "Chillán Viejo");
        INSERT INTO "comunas" ("id", "nombre") VALUES (201, "El Carmen");
        INSERT INTO "comunas" ("id", "nombre") VALUES (202, "Pemuco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (203, "Pinto");
        INSERT INTO "comunas" ("id", "nombre") VALUES (204, "Quillón");
        INSERT INTO "comunas" ("id", "nombre") VALUES (205, "San Ignacio");
        INSERT INTO "comunas" ("id", "nombre") VALUES (206, "Yungay");
        INSERT INTO "comunas" ("id", "nombre") VALUES (207, "Cobquecura");
        INSERT INTO "comunas" ("id", "nombre") VALUES (208, "Coelemu");
        INSERT INTO "comunas" ("id", "nombre") VALUES (209, "Ninhue");
        INSERT INTO "comunas" ("id", "nombre") VALUES (210, "Portezuelo");
        INSERT INTO "comunas" ("id", "nombre") VALUES (211, "Quirihue");
        INSERT INTO "comunas" ("id", "nombre") VALUES (212, "Ránquil");
        INSERT INTO "comunas" ("id", "nombre") VALUES (213, "Treguaco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (214, "San Carlos");
        INSERT INTO "comunas" ("id", "nombre") VALUES (215, "Coihueco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (216, "San Nicolás");
        INSERT INTO "comunas" ("id", "nombre") VALUES (217, "Ñiquén");
        INSERT INTO "comunas" ("id", "nombre") VALUES (218, "San Fabián");
        INSERT INTO "comunas" ("id", "nombre") VALUES (219, "Alto Biobío");
        INSERT INTO "comunas" ("id", "nombre") VALUES (220, "Antuco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (221, "Cabrero");
        INSERT INTO "comunas" ("id", "nombre") VALUES (222, "Laja");
        INSERT INTO "comunas" ("id", "nombre") VALUES (223, "Los Ángeles");
        INSERT INTO "comunas" ("id", "nombre") VALUES (224, "Mulchén");
        INSERT INTO "comunas" ("id", "nombre") VALUES (225, "Nacimiento");
        INSERT INTO "comunas" ("id", "nombre") VALUES (226, "Negrete");
        INSERT INTO "comunas" ("id", "nombre") VALUES (227, "Quilaco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (228, "Quilleco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (229, "San Rosendo");
        INSERT INTO "comunas" ("id", "nombre") VALUES (230, "Santa Bárbara");
        INSERT INTO "comunas" ("id", "nombre") VALUES (231, "Tucapel");
        INSERT INTO "comunas" ("id", "nombre") VALUES (232, "Yumbel");
        INSERT INTO "comunas" ("id", "nombre") VALUES (233, "Concepción");
        INSERT INTO "comunas" ("id", "nombre") VALUES (234, "Coronel");
        INSERT INTO "comunas" ("id", "nombre") VALUES (235, "Chiguayante");
        INSERT INTO "comunas" ("id", "nombre") VALUES (236, "Florida");
        INSERT INTO "comunas" ("id", "nombre") VALUES (237, "Hualpén");
        INSERT INTO "comunas" ("id", "nombre") VALUES (238, "Hualqui");
        INSERT INTO "comunas" ("id", "nombre") VALUES (239, "Lota");
        INSERT INTO "comunas" ("id", "nombre") VALUES (240, "Penco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (241, "San Pedro de La Paz");
        INSERT INTO "comunas" ("id", "nombre") VALUES (242, "Santa Juana");
        INSERT INTO "comunas" ("id", "nombre") VALUES (243, "Talcahuano");
        INSERT INTO "comunas" ("id", "nombre") VALUES (244, "Tomé");
        INSERT INTO "comunas" ("id", "nombre") VALUES (245, "Arauco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (246, "Cañete");
        INSERT INTO "comunas" ("id", "nombre") VALUES (247, "Contulmo");
        INSERT INTO "comunas" ("id", "nombre") VALUES (248, "Curanilahue");
        INSERT INTO "comunas" ("id", "nombre") VALUES (249, "Lebu");
        INSERT INTO "comunas" ("id", "nombre") VALUES (250, "Los Álamos");
        INSERT INTO "comunas" ("id", "nombre") VALUES (251, "Tirúa");
        INSERT INTO "comunas" ("id", "nombre") VALUES (252, "Angol");
        INSERT INTO "comunas" ("id", "nombre") VALUES (253, "Collipulli");
        INSERT INTO "comunas" ("id", "nombre") VALUES (254, "Curacautín");
        INSERT INTO "comunas" ("id", "nombre") VALUES (255, "Ercilla");
        INSERT INTO "comunas" ("id", "nombre") VALUES (256, "Lonquimay");
        INSERT INTO "comunas" ("id", "nombre") VALUES (257, "Los Sauces");
        INSERT INTO "comunas" ("id", "nombre") VALUES (258, "Lumaco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (259, "Purén");
        INSERT INTO "comunas" ("id", "nombre") VALUES (260, "Renaico");
        INSERT INTO "comunas" ("id", "nombre") VALUES (261, "Traiguén");
        INSERT INTO "comunas" ("id", "nombre") VALUES (262, "Victoria");
        INSERT INTO "comunas" ("id", "nombre") VALUES (263, "Temuco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (264, "Carahue");
        INSERT INTO "comunas" ("id", "nombre") VALUES (265, "Cholchol");
        INSERT INTO "comunas" ("id", "nombre") VALUES (266, "Cunco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (267, "Curarrehue");
        INSERT INTO "comunas" ("id", "nombre") VALUES (268, "Freire");
        INSERT INTO "comunas" ("id", "nombre") VALUES (269, "Galvarino");
        INSERT INTO "comunas" ("id", "nombre") VALUES (270, "Gorbea");
        INSERT INTO "comunas" ("id", "nombre") VALUES (271, "Lautaro");
        INSERT INTO "comunas" ("id", "nombre") VALUES (272, "Loncoche");
        INSERT INTO "comunas" ("id", "nombre") VALUES (273, "Melipeuco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (274, "Nueva Imperial");
        INSERT INTO "comunas" ("id", "nombre") VALUES (275, "Padre Las Casas");
        INSERT INTO "comunas" ("id", "nombre") VALUES (276, "Perquenco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (277, "Pitrufquén");
        INSERT INTO "comunas" ("id", "nombre") VALUES (278, "Pucón");
        INSERT INTO "comunas" ("id", "nombre") VALUES (279, "Saavedra");
        INSERT INTO "comunas" ("id", "nombre") VALUES (280, "Teodoro Schmidt");
        INSERT INTO "comunas" ("id", "nombre") VALUES (281, "Toltén");
        INSERT INTO "comunas" ("id", "nombre") VALUES (282, "Vilcún");
        INSERT INTO "comunas" ("id", "nombre") VALUES (283, "Villarrica");
        INSERT INTO "comunas" ("id", "nombre") VALUES (284, "Valdivia");
        INSERT INTO "comunas" ("id", "nombre") VALUES (285, "Corral");
        INSERT INTO "comunas" ("id", "nombre") VALUES (286, "Lanco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (287, "Los Lagos");
        INSERT INTO "comunas" ("id", "nombre") VALUES (288, "Máfil");
        INSERT INTO "comunas" ("id", "nombre") VALUES (289, "Mariquina");
        INSERT INTO "comunas" ("id", "nombre") VALUES (290, "Paillaco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (291, "Panguipulli");
        INSERT INTO "comunas" ("id", "nombre") VALUES (292, "La Unión");
        INSERT INTO "comunas" ("id", "nombre") VALUES (293, "Futrono");
        INSERT INTO "comunas" ("id", "nombre") VALUES (294, "Lago Ranco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (295, "Río Bueno");
        INSERT INTO "comunas" ("id", "nombre") VALUES (297, "Osorno");
        INSERT INTO "comunas" ("id", "nombre") VALUES (298, "Puerto Octay");
        INSERT INTO "comunas" ("id", "nombre") VALUES (299, "Purranque");
        INSERT INTO "comunas" ("id", "nombre") VALUES (300, "Puyehue");
        INSERT INTO "comunas" ("id", "nombre") VALUES (301, "Río Negro");
        INSERT INTO "comunas" ("id", "nombre") VALUES (302, "San Juan de la Costa");
        INSERT INTO "comunas" ("id", "nombre") VALUES (303, "San Pablo");
        INSERT INTO "comunas" ("id", "nombre") VALUES (304, "Calbuco");
        INSERT INTO "comunas" ("id", "nombre") VALUES (305, "Cochamó");
        INSERT INTO "comunas" ("id", "nombre") VALUES (306, "Fresia");
        INSERT INTO "comunas" ("id", "nombre") VALUES (307, "Frutillar");
        INSERT INTO "comunas" ("id", "nombre") VALUES (308, "Llanquihue");
        INSERT INTO "comunas" ("id", "nombre") VALUES (309, "Los Muermos");
        INSERT INTO "comunas" ("id", "nombre") VALUES (310, "Maullín");
        INSERT INTO "comunas" ("id", "nombre") VALUES (311, "Puerto Montt");
        INSERT INTO "comunas" ("id", "nombre") VALUES (312, "Puerto Varas");
        INSERT INTO "comunas" ("id", "nombre") VALUES (313, "Ancud");
        INSERT INTO "comunas" ("id", "nombre") VALUES (314, "Castro");
        INSERT INTO "comunas" ("id", "nombre") VALUES (315, "Chonchi");
        INSERT INTO "comunas" ("id", "nombre") VALUES (316, "Curaco de Vélez");
        INSERT INTO "comunas" ("id", "nombre") VALUES (317, "Dalcahue");
        INSERT INTO "comunas" ("id", "nombre") VALUES (318, "Puqueldón");
        INSERT INTO "comunas" ("id", "nombre") VALUES (319, "Queilén");
        INSERT INTO "comunas" ("id", "nombre") VALUES (320, "Quellón");
        INSERT INTO "comunas" ("id", "nombre") VALUES (321, "Quemchi");
        INSERT INTO "comunas" ("id", "nombre") VALUES (322, "Quinchao");
        INSERT INTO "comunas" ("id", "nombre") VALUES (323, "Chaitén");
        INSERT INTO "comunas" ("id", "nombre") VALUES (324, "Futaleufú");
        INSERT INTO "comunas" ("id", "nombre") VALUES (325, "Hualaihué");
        INSERT INTO "comunas" ("id", "nombre") VALUES (326, "Palena");
        INSERT INTO "comunas" ("id", "nombre") VALUES (327, "Lago Verde");
        INSERT INTO "comunas" ("id", "nombre") VALUES (328, "Coihaique");
        INSERT INTO "comunas" ("id", "nombre") VALUES (329, "Aysén");
        INSERT INTO "comunas" ("id", "nombre") VALUES (330, "Cisnes");
        INSERT INTO "comunas" ("id", "nombre") VALUES (331, "Guaitecas");
        INSERT INTO "comunas" ("id", "nombre") VALUES (332, "Río Ibáñez");
        INSERT INTO "comunas" ("id", "nombre") VALUES (333, "Chile Chico");
        INSERT INTO "comunas" ("id", "nombre") VALUES (334, "Cochrane");
        INSERT INTO "comunas" ("id", "nombre") VALUES (335, "O""higgins");
        INSERT INTO "comunas" ("id", "nombre") VALUES (336, "Tortel");
        INSERT INTO "comunas" ("id", "nombre") VALUES (337, "Natales");
        INSERT INTO "comunas" ("id", "nombre") VALUES (338, "Torres del Paine");
        INSERT INTO "comunas" ("id", "nombre") VALUES (339, "Laguna Blanca");
        INSERT INTO "comunas" ("id", "nombre") VALUES (340, "Punta Arenas");
        INSERT INTO "comunas" ("id", "nombre") VALUES (341, "Río Verde");
        INSERT INTO "comunas" ("id", "nombre") VALUES (342, "San Gregorio");
        INSERT INTO "comunas" ("id", "nombre") VALUES (343, "Porvenir");
        INSERT INTO "comunas" ("id", "nombre") VALUES (344, "Primavera");
        INSERT INTO "comunas" ("id", "nombre") VALUES (345, "Timaukel");
        INSERT INTO "comunas" ("id", "nombre") VALUES (346, "Cabo de Hornos");
        INSERT INTO "comunas" ("id", "nombre") VALUES (347, "Antártica");
        INSERT INTO "comunas" ("id", "nombre") VALUES (348, "San Francisco de Mostazal");';

        DB::unprepared($sqlComunas);
    }
}
